# -*- coding: utf-8 -*-
"""zad3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kk2-sQcTNwy4Nb8ynL6Ddg8BE_ky2bPl
"""

import math
def policz1(x,y):
  return y*math.sqrt((x/y)**2+1)
print(policz1(9.8**201,10.2**199))

import math
def policz2(x,y):
  return math.sqrt(x**2+y**2)
print(policz2(9.8**201,10.2**199))

#Bezpieczniej jest używać pierwszego równania.